### ISSUE TITLE
Not working (ubuntu)

### ISSUE THREAD

**Issue by rygo6** [mbasso/asm-dom-boilerplate#5]
I just tried to compile and run your project, nothing renders and it put out this error:

```
ryan@ryan-ubuntu:~/Developer/asm-dom-boilerplate$ npm start

> asm-dom-boilerplate@0.1.0 start /home/ryan/Developer/asm-dom-boilerplate
> make start

npx concurrently \
	-p "[{name}]" \
	-n "Parcel,Make" \
	-c "bgGreen.bold,bgBlue.bold" \
	"npx cross-env NODE_ENV=development parcel index.html --open" \
	"nodemon --exec \"make dist/wasm dist/asmjs\""
[Make] [nodemon] 1.17.4
[Make] [nodemon] reading config ./nodemon.json
[Make] [nodemon] to restart at any time, enter `rs`
[Make] [nodemon] or send SIGHUP to 8719 to restart
[Make] [nodemon] ignoring: ./.git/**/* ./glue/**/* ./dist/**/* ./.cache/**/* ./temp/**/* node_modules/**/node_modules
[Make] [nodemon] watching: /home/ryan/Developer/asm-dom-boilerplate/src/**/*
[Make] [nodemon] watching extensions: c,cpp,h,hpp
[Make] [nodemon] starting `make dist/wasm dist/asmjs`
[Make] [nodemon] spawning
[Make] [nodemon] child pid: 8742
[Make] make[1]: Entering directory '/home/ryan/Developer/asm-dom-boilerplate'
[Make] make[1]: 'dist/wasm' is up to date.
[Make] make[1]: 'dist/asmjs' is up to date.
[Make] make[1]: Leaving directory '/home/ryan/Developer/asm-dom-boilerplate'
[Make] [nodemon] clean exit - waiting for changes before restart
[Make] [nodemon] watching 3 files
[Parcel] Server running at http://localhost:1234 
⏳  Building index.js...
events.js:183
[Parcel]       throw er; // Unhandled 'error' event
[Parcel]       ^
[Parcel] 
[Parcel] Error: watch /home/ryan/Developer/asm-dom-boilerplate/node_modules/pause-stream/test/index.js ENOSPC
[Parcel]     at _errnoException (util.js:1024:11)
[Parcel]     at FSWatcher.start (fs.js:1374:19)
[Parcel]     at Object.fs.watch (fs.js:1400:11)
[Parcel]     at createFsWatchInstance (/home/ryan/Developer/asm-dom-boilerplate/node_modules/parcel-bundler/node_modules/chokidar/lib/nodefs-handler.js:37:15)
[Parcel]     at setFsWatchListener (/home/ryan/Developer/asm-dom-boilerplate/node_modules/parcel-bundler/node_modules/chokidar/lib/nodefs-handler.js:80:15)
[Parcel]     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/ryan/Developer/asm-dom-boilerplate/node_modules/parcel-bundler/node_modules/chokidar/lib/nodefs-handler.js:232:14)
[Parcel]     at FSWatcher.NodeFsHandler._handleFile (/home/ryan/Developer/asm-dom-boilerplate/node_modules/parcel-bundler/node_modules/chokidar/lib/nodefs-handler.js:259:21)
[Parcel]     at FSWatcher.<anonymous> (/home/ryan/Developer/asm-dom-boilerplate/node_modules/parcel-bundler/node_modules/chokidar/lib/nodefs-handler.js:480:21)
[Parcel]     at FSReqWrap.oncomplete (fs.js:153:5)
[Parcel] npx cross-env NODE_ENV=development parcel index.html --open exited with code 1
```

Also just to make sure:
```
ryan@ryan-ubuntu:~/Developer/asm-dom-boilerplate$ make -v
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
ryan@ryan-ubuntu:~/Developer/asm-dom-boilerplate$ node -v
v8.9.1
ryan@ryan-ubuntu:~/Developer/asm-dom-boilerplate$ npm -v
6.4.0
ryan@ryan-ubuntu:~/Developer/asm-dom-boilerplate$ make -v
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
ryan@ryan-ubuntu:~/Developer/asm-dom-boilerplate$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.11
clang version 6.0.1  (emscripten 1.38.11 : 1.38.11)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/ryan/Developer/emsdk/clang/e1.38.11_64bit
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8.0.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8.0.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
INFO:root:(Emscripten: Running sanity checks)
```

Any help would be appreciated. Would really like to try making a page in C++.

**Comment by rygo6** [comment]
I found this command 
```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

from here 
https://stackoverflow.com/questions/22475849/node-js-error-enospc

and that fixed it.

Don't know why, but would like to understand how that relates to this project.

**Comment by mbasso** [comment]
Hi @rygo6,
thank you for your interest in asm-dom and for opening this issue.
The problem seems to be related to the watcher used by this project to automatically recompile C++ files. I've found [this link](https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers#the-technical-details) that explains the command. I don't know if we can do anything to avoid that. Have you ideas?
